### ISSUE TITLE
构建项目的时候报错

### ISSUE THREAD

**Issue by jgsrty** [JamesZBL/keykee#6]
![image](https://user-images.githubusercontent.com/25652828/51578916-22710400-1efa-11e9-8764-4b83a0c22b66.png)

**Comment by JamesZBL** [comment]
需要先安装 pyinstaller

**Comment by jgsrty** [comment]
![image](https://user-images.githubusercontent.com/25652828/51585466-725cc480-1f14-11e9-9358-5ad940c77dbb.png)
还是不行啊 
装了有python、pip、umi、pyinstaller 还是不行
